unbind C-b               # unbind default prefix
set -g prefix C-Space    # set prefix to ctrl+a
bind C-Space send-prefix # rebind prefix to ctrl+a

set -g mouse on

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set -sg escape-time 10 # quicker responses to escape key presses

# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'

# set -g @mythm_bg "#080808"
set -g @mythm_bg "#020202"

set -g status-bg "#020202"

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100

# for Running command
set -g @modBG0 "#073038"
set -g @iconFG0 "#3ed80f"
set -g @txtFG0 "#eaeaea"
set -g status-left "#[fg=#{@modBG0},bg=#{@mythm_bg}]#[fg=#{@iconFG0},bg=#{@modBG0}]󰅭 #[fg=#{@txtFG0},bg=#{@modBG0}] #{pane_current_command} #[fg=#{@modBG0},bg=#{@mythm_bg}] "

# for directory
set -g @modBG "#3a3c4e"
set -g @iconFG1 "#3ed80f"
set -g @txtFG "#eaeaea"
set -g status-right "#[fg=#{@modBG},bg=#{@mythm_bg}]#[fg=#{@iconFG1},bg=#{@modBG}]#[fg=#{@txtFG},bg=#{@modBG}] #{b:pane_current_path} #[fg=#{@modBG},bg=#{@mythm_bg}] "

# for hostname
set -g @modBG "#3a3c4e"
set -g @iconFG3 "#eed40e"
set -g @txtFG "#eaeaea"
set -ag status-right "#[fg=#{@modBG},bg=#{@mythm_bg}]#[fg=#{@iconFG3},bg=#{@modBG}]󰒋 #[fg=#{@txtFG},bg=#{@modBG}]#h#[fg=#{@modBG},bg=#{@mythm_bg}] "

# for session
set -g @modBG "#3a3c4e"
set -g @iconFG2 "#16a6ca"
set -g @txtFG "#eaeaea"
set -ag status-right "#[fg=#{@modBG},bg=#{@mythm_bg}]#[fg=#{@iconFG2},bg=#{@modBG}] #[fg=#{@txtFG},bg=#{@modBG}] #S #[fg=#{@modBG},bg=#{@mythm_bg}] "

set -g @winBGActive "#ab5dac"
set -g @winBGInactive "#3a3c4e"
set -g @numberFG "#bfbfbf"
set -g @txtFG "#eaeaea"
set -g window-status-current-format "#[bold,fg=#{@winBGActive},bg=#{@mythm_bg}]#[fg=#{@numberFG},bg=#{@winBGActive}]#I #[fg=#{@txtFG},bg=#{@winBGInactive}] #W#[fg=#{@winBGInactive},bg=#{@mythm_bg}] "

set -g window-status-format "#[fg=#292929,bg=#{@mythm_bg}]#[fg=#{@numberFG},bg=#292929]#I #[fg=#{@txtFG},bg=#{@winBGInactive}] #W#[fg=#{@winBGInactive},bg=#{@mythm_bg}] "

set -g message-style "bg=#020202,fg=#1c8984,bold"
set -g mode-style "bg=#36504b,fg=#ffffff"
#
#
#
#
#
#
#
#
#
# Initialize TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'

